name: GCloud Build
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/*yaml'
      - 'readme/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/*yaml'
      - 'readme/**'
      
  workflow_dispatch:

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    env:
      GAR_INFO: us-central1-docker.pkg.dev/triangulum-ctv/stans-robot-shop
      SHIPPING_APP_NAME: rs-shipping
      TAG: 1.0.0

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
     # -
     #   name: Docker meta
     #   id: docker_meta
     #   uses: docker/metadata-action@v3
     #   with:
     #     images: |
     #       $GAR_INFO"/"$SHIPPING_APP_NAME"
     #     tags: |
     #       type=ref,event=branch
     #       type=ref,event=tag
     #       type=ref,event=pr
     #       type=semver,pattern=v{{version}}
     #       type=semver,pattern=v{{major}}.{{minor}}
     #       type=semver,pattern=v{{major}}
     #       type=sha

      - name: Setup GCP Service Account
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
      
      - name: Use gcloud CLI
        run: "gcloud info"

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Setup Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build the Docker image
      # export TAG=`echo $GITHUB_REF | awk -F/ '{print $NF}'`
      # export TAG=${{ steps.docker_meta.outputs.tags }}
      
      - name: Build
        run: |
          echo $TAG
          echo "$GAR_INFO"/"$SHIPPING_APP_NAME":"$TAG"
          docker build -t "$GAR_INFO"/"$SHIPPING_APP_NAME":"$TAG" shipping/
          gcloud info
          docker push "$GAR_INFO"/"$SHIPPING_APP_NAME":"$TAG"

      # docker build -t us-central1-docker.pkg.dev/triangulum-ctv/stans-robot-shop/rs-shipping:"$TAG" shipping/
      # Push the Docker image to Google Container Registry
          
      - name: Publish
        run: |
          gcloud info
          NEW_TAG="$TAG.1"
          echo $TAG
          docker tag "$GAR_INFO"/"$SHIPPING_APP_NAME":"$TAG" "$GAR_INFO"/"$SHIPPING_APP_NAME":"$NEW_TAG"
          docker push "$GAR_INFO"/"$SHIPPING_APP_NAME":"$NEW_TAG"