# Prepare Your Workflow for Authentication to various systems needed for the execution
# Setup GITHUB SECRETS, GITHUB_TOKEN If necessary
# Setup DOCKER CREDENTIALS
# Setup GOOGLE CREDENTIALS

name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/*yaml'
      - 'readme/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/*yaml'
      - 'readme/**'
      
  workflow_dispatch:

jobs:
  build_roboshop_images:
    name: Build Robot Shop Images
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      # Dumping context for getting env settings and output variables
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Dump job context
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      
      - name: Dump runner context
        if: always()
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      # Perform Chekout of the Code

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKERHUB_USER }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:shipping"
          push: false
          tags: rs-shipping:$TAG

      #- name: Setup Docker Buildx
      #  uses: docker/setup-buildx-action@v1

      #- name: Check some Info
      #  run: |
      #    echo "Working directory is: $GITHUB_WORKSPACE"
      #   echo "Listing Contents"
      #    ls -al

      #- name: Build Docker Images
      #  id: docker-builder
      #  run: |
      #    echo "-----Building Shipping Docker Images-----"
      #    #docker-compose -f docker-compose.yaml build
      #    docker build -t rs-shipping:$TAG -f shipping/Dockerfile .
      
      - name: List Docker Images
        run: | 
          echo ${{ steps.docker-builder.outputs.name }}
          docker images ls

# Configuring a new Job for tagging and pushing images to Google Artifact Registry

  push_roboshop_images:
    name: Push Robot Shop Images to GCR
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder
        run: echo "Hello you are seeing Job2"
